ci: Fix CI with newer MSVC by removing the Qt5 workflow
Qt5 is now rotting and fails to build with recent MSVC:
   error C2653: 'stdext': is not a class or namespace name in qvector.h

KDChart will still build with Qt5 if you patch Qt, but there's probably
0 such users out there. Please upgrade to Qt6 or contact us for a
patch.