KDGantt: Undefine `d` before including Qt headers
Otherwise breaks qmutex.h:

```.../qmutex.h:153:33: error: invalid pure specifier (only ‘= 0’ is allowed) before ‘.’ token
  153 |         QMutexPrivate *d = d_ptr.loadRelaxed();
      |                                 ^